
import "../globals.css";
import {
  inter,
  roboto_mono,
  dosis,
  montserrat,
  marcellus,
  forum,
  caudex,
  maven,
  mukta,
  laBelle,
} from "@/lib/fonts";
import {MenubarAdmin} from './superAdminHeader'



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${roboto_mono.variable} ${dosis.variable} ${dosis.variable} ${marcellus.variable} ${montserrat.variable} ${forum.variable} ${caudex.variable} ${mukta.variable} ${laBelle.variable} ${maven.variable} `}
    >
      <body>
    
      <MenubarAdmin />
        {children}
         
       
      </body>
    </html>
  );
}
