import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import CatalogProvider from '@/context_store/catalogProvider'
import AuthProvider from '@/app/auth/authprovider' 
import {
  inter,
  roboto_mono,
  dosis,
  montserrat,
  marcellus,
  forum,
  caudex,
  maven,
  mukta,
  laBelle,
} from "@/lib/fonts";
// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'NHMP QUIZ ',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${roboto_mono.variable} ${dosis.variable} ${dosis.variable} ${marcellus.variable} ${montserrat.variable} ${forum.variable} ${caudex.variable} ${mukta.variable} ${laBelle.variable} ${maven.variable} `}
    >
      <body className={inter.className}>
      <AuthProvider>
        <CatalogProvider>
        {children}
        </CatalogProvider>
        </AuthProvider>
        </body>
    </html>
  )
}
